name: CN10Y Watcher

on:
  workflow_dispatch:
  schedule:
    # UTC 时间 00:10 运行（相当于北京时间 09:10）
    - cron: "10 0 * * 1-5"

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run monitor
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor_cn10y.py
